#!/usr/bin/env python3
"""Proof that todo.py still agrees with the board.

The format is understood twice: in JavaScript in core/todo.js, which the board
loads, and in Python here in core/todo.py. Two copies of one set of rules is a
standing invitation to drift, and drift here is quiet — a meeting rolls to the
wrong Thursday and nothing complains.

It used to be three, the third being a hand-transcribed copy inside
pa-checkin/scripts/check_todo.py. That one is gone: the checker imports
core/todo.py from the repo, or the copy build.command stages beside it in the
zip. The JavaScript is the one that cannot import, because the board is a single
HTML file, so it is the one these tables exist to pin.

The tables are not in this file any more. They live in core/fixtures/ as JSON,
and core/test_todo.mjs reads the same three files and runs the same checks
against core/todo.js. Two suites, one set of answers — a table transcribed into
each language would be a third copy to keep in step, which is the problem this
is here to solve. Run both:

    python3 core/test_todo.py
    node core/test_todo.mjs

Every table was generated by running the board's own functions, so they hold the
board's answers rather than a second opinion.

  fixtures/repeat.json    thirty tag forms, each asked for its next occurrence
                          from seven days in each of fourteen months, and then
                          walked twelve occurrences from a fixed anchor. Between
                          them that covers month-end clamping, February, the nth
                          working day landing later in a short month, the
                          December rollover, and the `/n` intervals — which are
                          invisible to occurrenceFrom and only show up in a walk.
  fixtures/messages.json  the suggested-message notes, including curly quotes, a
                          colon inside the text, and a message written without
                          quotes at all.
  fixtures/parse.json     a task line carrying every tag, and the junk-input
                          edges where the two used to disagree: `****` as a
                          title, `rank:3px`, a numbered bucket below Context.
                          It pins what the board *writes* as well, which is the
                          one thing Python cannot check — todo.py has no
                          serialiser — so those columns are the JavaScript
                          suite's alone.

The calendar tables stay in this file, because there is nothing on the other
side to compare them against: the board has no working calendar and deliberately
never will. Those dates are worked out from the rules rather than typed in, which
is what stops the list expiring — and also what makes a quiet mistake possible,
since nothing complains if a rule is subtly wrong. The two tables below are the
published holidays for 2026 and 2027.

They were checked against the sources on 4 Sep 2026, and `--online` runs that
same check again: gov.uk's own feed for England and Wales, and Nager.Date for
Portugal, which has no official feed. Every England-and-Wales date from 2019 to
2028 agreed, apart from the five one-off events no rule can produce — the VE Day
move, the Jubilee, the State Funeral and the Coronation — which are written into
todo.UK_EXTRA and checked here too. Both Portuguese years agreed exactly.

The offline tables are what run by default. A test that needs the network is a
test that fails on a train.

    python3 core/test_todo.py             the pinned tables
    python3 core/test_todo.py --online    and again against the sources
"""

import calendar
import datetime as dt
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import todo



# ---- the fixtures ----------------------------------------------------------
#
# core/fixtures/ holds every table both suites read. Nothing below transcribes
# one: a table written out twice, once per language, is the third copy this file
# exists to prevent.
FIXTURES = os.path.join(os.path.dirname(os.path.abspath(__file__)), "fixtures")


def fixture(name):
    with open(os.path.join(FIXTURES, name), encoding="utf-8") as fh:
        return json.load(fh)


REPEAT = fixture("repeat.json")
SEED_DAYS = REPEAT["seedDays"]
SEED_MONTHS = REPEAT["seedMonths"]
START_YEAR = REPEAT["startYear"]
ANCHOR = dt.date.fromisoformat(REPEAT["anchor"])
# (tag, the label the board draws, its next occurrence from every seed date, and
# a run of twelve consecutive occurrences from the anchor).
# A label of None means the board rejects the tag, and so must this.
#
# The run is what tests an interval. One lives entirely in occurrence_after —
# occurrence_from answers "the next Wednesday", which has no phase to get wrong —
# so a fortnightly tag is indistinguishable from a weekly one until you walk a
# series. Twelve is enough to cross a year boundary on every form here.
CASES = [(c["tag"], c["label"], c["dates"], c["series"]) for c in REPEAT["cases"]]



# Every England-and-Wales bank holiday for two years, including the substitute
# days — 2027 is the interesting one, where Christmas on a Saturday pushes
# Boxing Day to the Tuesday.
UK_HOLIDAYS = {
    "2026-01-01": "New Year's Day",
    "2026-04-03": "Good Friday",
    "2026-04-06": "Easter Monday",
    "2026-05-04": "Early May bank holiday",
    "2026-05-25": "Spring bank holiday",
    "2026-08-31": "Summer bank holiday",
    "2026-12-25": "Christmas Day",
    "2026-12-28": "Boxing Day (substitute)",
    "2027-01-01": "New Year's Day",
    "2027-03-26": "Good Friday",
    "2027-03-29": "Easter Monday",
    "2027-05-03": "Early May bank holiday",
    "2027-05-31": "Spring bank holiday",
    "2027-08-30": "Summer bank holiday",
    "2027-12-27": "Christmas Day (substitute)",
    "2027-12-28": "Boxing Day (substitute)",
}

# Portugal's national set. No substitution here, which is why 2027 loses four of
# them to a weekend and nothing moves.
PT_HOLIDAYS = {
    "2026-01-01": "Ano Novo",
    "2026-02-17": "Carnaval (tolerância de ponto)",
    "2026-04-03": "Sexta-feira Santa",
    "2026-04-05": "Domingo de Páscoa",
    "2026-04-25": "Dia da Liberdade",
    "2026-05-01": "Dia do Trabalhador",
    "2026-06-04": "Corpo de Deus",
    "2026-06-10": "Dia de Portugal",
    "2026-08-15": "Assunção de Nossa Senhora",
    "2026-10-05": "Implantação da República",
    "2026-11-01": "Dia de Todos-os-Santos",
    "2026-12-01": "Restauração da Independência",
    "2026-12-08": "Imaculada Conceição",
    "2026-12-25": "Natal",
    "2027-01-01": "Ano Novo",
    "2027-02-09": "Carnaval (tolerância de ponto)",
    "2027-03-26": "Sexta-feira Santa",
    "2027-03-28": "Domingo de Páscoa",
    "2027-04-25": "Dia da Liberdade",
    "2027-05-01": "Dia do Trabalhador",
    "2027-05-27": "Corpo de Deus",
    "2027-06-10": "Dia de Portugal",
    "2027-08-15": "Assunção de Nossa Senhora",
    "2027-10-05": "Implantação da República",
    "2027-11-01": "Dia de Todos-os-Santos",
    "2027-12-01": "Restauração da Independência",
    "2027-12-08": "Imaculada Conceição",
    "2027-12-25": "Natal",
}

# Every England-and-Wales departure from the rules since gov.uk's feed begins.
# They are in the past and nothing reads them; they are pinned because they are
# what proves todo.UK_EXTRA can move a holiday as well as add one, which is the
# thing that will be needed the next time the government does this.
UK_OVERRIDES = {
    "2020-05-04": None,
    "2020-05-08": "Early May bank holiday (VE day)",
    "2022-05-30": None,
    "2022-06-02": "Spring bank holiday",
    "2022-06-03": "Platinum Jubilee bank holiday",
    "2022-09-19": "Bank Holiday for the State Funeral of Queen Elizabeth II",
    "2023-05-08": "Bank holiday for the coronation of King Charles III",
}

# Easter drives seven of the entries above, so it is worth pinning on its own —
# a wrong Easter is a wrong Good Friday, Corpo de Deus and Carnaval at once.
EASTERS = {2024: "2024-03-31", 2025: "2025-04-20", 2026: "2026-04-05",
           2027: "2027-03-28", 2028: "2028-04-16", 2030: "2030-04-21",
           2035: "2035-03-25", 2040: "2040-04-01"}


def check_calendar():
    """The generated holidays against the published ones, both ways: nothing
    real is missing, and nothing is invented on a day that is an ordinary
    working day."""
    failures = 0
    for year, iso in EASTERS.items():
        got = todo.easter_sunday(year).isoformat()
        if got != iso:
            print("FAIL Easter %d gave %s, should be %s" % (year, got, iso))
            failures += 1
    for region, want in (("UK", UK_HOLIDAYS), ("PT", PT_HOLIDAYS)):
        got = {}
        for year in (2026, 2027):
            got.update({d.isoformat(): n
                        for d, n in todo.holidays(year, (region,))[region].items()})
        for iso in sorted(set(want) | set(got)):
            if iso not in got:
                print("FAIL %s %s missing: should be %s" % (region, iso, want[iso]))
                failures += 1
            elif iso not in want:
                print("FAIL %s %s invented: %s" % (region, iso, got[iso]))
                failures += 1
            elif got[iso] != want[iso]:
                print("FAIL %s %s named %r, should be %r" % (region, iso, got[iso], want[iso]))
                failures += 1
    for iso, name in UK_OVERRIDES.items():
        got = todo.holiday_name(dt.date.fromisoformat(iso), ("UK",))
        if got != name:
            print("FAIL override %s gave %r, should be %r" % (iso, got, name))
            failures += 1
    # And the answer the callers actually ask for.
    for iso, reason in (("2026-12-25", "Christmas Day, a public holiday in the UK and Portugal"),
                        ("2026-06-10", "Dia de Portugal, a Portuguese public holiday"),
                        ("2026-05-25", "Spring bank holiday, a UK bank holiday"),
                        ("2026-04-25", "a Saturday"),
                        ("2026-09-04", None)):
        got = todo.non_working_reason(dt.date.fromisoformat(iso))
        if got != reason:
            print("FAIL %s reads %r, should be %r" % (iso, got, reason))
            failures += 1
    total = len(UK_HOLIDAYS) + len(PT_HOLIDAYS) + len(EASTERS) + len(UK_OVERRIDES)
    print("%d holidays, overrides and Easters — %s"
          % (total, "all agree" if not failures else "%d failed" % failures))
    return failures


def check_calendar_online():
    """The generated calendar against the published sources, live.

    gov.uk publishes England and Wales as JSON and is the authority for it.
    Portugal has no equivalent feed, so Nager.Date stands in — an independent
    reading rather than a primary source, which is worth exactly as much as a
    second opinion and no more. A source that will not answer is reported and
    skipped, not failed: an outage is not a bug in this file."""
    import json
    import subprocess
    import urllib.request

    def get(url):
        """urllib, then curl. A framework Python installed without running its
        own Install Certificates step has no CA bundle and refuses every HTTPS
        call, which is a machine problem rather than a reason to skip the
        check — and curl on macOS uses the system trust store regardless."""
        try:
            with urllib.request.urlopen(url, timeout=20) as fh:
                return json.load(fh)
        except Exception:
            pass
        try:
            out = subprocess.run(["/usr/bin/curl", "-sS", "--max-time", "20", url],
                                 capture_output=True, timeout=30)
            if out.returncode == 0 and out.stdout:
                return json.loads(out.stdout)
            print("  could not reach %s (%s)" % (url, out.stderr.decode().strip()))
        except Exception as exc:
            print("  could not reach %s (%s)" % (url, exc))
        return None

    failures = 0
    feed = get("https://www.gov.uk/bank-holidays.json")
    if feed:
        events = feed["england-and-wales"]["events"]
        years = sorted({int(e["date"][:4]) for e in events})
        official = {e["date"] for e in events}
        mine = set()
        for year in years:
            mine |= {d.isoformat() for d in todo.holidays(year, ("UK",))["UK"]}
        for iso in sorted(official ^ mine):
            where = "gov.uk only" if iso in official else "ours only"
            print("FAIL UK %s — %s" % (iso, where))
            failures += 1
        print("  gov.uk %d-%d: %d dates, %s"
              % (years[0], years[-1], len(official),
                 "all agree" if not failures else "see above"))

    for year in (2026, 2027):
        src = get("https://date.nager.at/api/v3/PublicHolidays/%d/PT" % year)
        if not src:
            continue
        # Regional only — the Azores, Madeira and the municipal days — is not
        # what this models, so `global` is the filter.
        official = {h["date"] for h in src if h.get("global")}
        mine = {d.isoformat() for d in todo.holidays(year, ("PT",))["PT"]}
        for iso in sorted(official ^ mine):
            where = "Nager only" if iso in official else "ours only"
            print("FAIL PT %s — %s" % (iso, where))
            failures += 1
        print("  Nager.Date PT %d: %d dates, %s"
              % (year, len(official), "all agree" if not official ^ mine else "see above"))
    return failures


def seeds():
    for m in range(SEED_MONTHS):
        y, mo = START_YEAR + m // 12, m % 12 + 1
        for day in SEED_DAYS:
            if day > calendar.monthrange(y, mo)[1]:
                continue
            yield dt.date(y, mo, day)


# ---- suggested messages -----------------------------------------------------
#
# The second thing the board and this file both have to agree about. Every line
# in the fixture was put through the board's own MSG_NOTE and quoted(), so a
# failure means todo.py has drifted from the board, not that somebody guessed
# wrong when writing the test. The awkward ones are deliberate: a colon inside
# the text breaks a naive split-on-colon reading, curly quotes are what arrives
# from anything with autocorrect in it, and a message with no quotes at all is
# the shape that survives being pasted out of an older file.
MESSAGES = fixture("messages.json")
MESSAGE_CASES = [(m["line"], m["matches"], m["draft"], m["text"])
                 for m in MESSAGES["lines"]]
# One task carrying the shapes that matter structurally: a message on the task
# itself, one on a live step, one on a step already ticked, and one on a step
# whose own due date differs from its parent's.
MESSAGE_DOC = MESSAGES["doc"]


def check_messages():
    failures = 0
    for line, matches, draft, text in MESSAGE_CASES:
        got = bool(todo.MSG_NOTE.search(line))
        if got != matches:
            print("FAIL message match %r — got %s, board says %s" % (line[:50], got, matches))
            failures += 1
            continue
        if not matches:
            continue
        mine = todo.quoted(line)
        if mine != text:
            print("FAIL message text %r\n     got  %r\n     board %r" % (line[:50], mine, text))
            failures += 1
        if ("(draft)" in line.lower()) != draft:
            print("FAIL message draft %r" % line[:50])
            failures += 1

    tasks = todo.parse_doc(MESSAGE_DOC)
    live = [m for t in tasks for m in todo.messages(t)]
    every = [m for t in tasks for m in todo.messages(t, live_only=False)]

    want_live = [(m["text"], m["where"], m["due"], m["draft"])
                 for m in MESSAGES["live"]]
    got_live = [(m["text"], m["where"], m["due"], m["draft"]) for m in live]
    if got_live != want_live:
        print("FAIL live messages\n     got  %r\n     want %r" % (got_live, want_live))
        failures += 1
    # A ticked step's message has been sent, and a ticked task takes its steps
    # with it — both are out of the live list and in the full one.
    if len(every) != MESSAGES["everyCount"]:
        print("FAIL every message: got %d, want %d"
              % (len(every), MESSAGES["everyCount"]))
        failures += 1
    print("%d message lines, %d in a document — %s"
          % (len(MESSAGE_CASES), len(every),
             "all agree" if not failures else "%d failed" % failures))
    return failures


# ---- the task line itself ---------------------------------------------------
#
# The third table, and the newest. It is what caught the three places these two
# had already drifted: `****` as a title, a `rank:` with junk after the number,
# and a numbered bucket written below Context. All three are junk or unreachable
# input, which is exactly why nobody noticed.
#
# The board is the authority, so in all three the Python moved. What it cannot
# check is the other half of the fixture — `roundTrip`, what the board writes
# back — because todo.py has no serialiser and deliberately never will. That
# column is core/test_todo.mjs's to answer.
PARSE = fixture("parse.json")
PRIORITY = fixture("priority.json")

# The board's names for the fields, and this file's. Only `bold` has no Python
# side: it exists to remember whether to put the asterisks back on write, which
# is a writer's question.
PY_FIELD = {"doneOn": "done_on", "blockedBy": "blocked_by"}
SKIP_FIELD = {"bold"}


def check_parse():
    failures = 0
    for case in PARSE["cases"]:
        task = todo.parse_task([case["line"]])
        for field, want in case["expect"].items():
            if field in SKIP_FIELD:
                continue
            got = getattr(task, PY_FIELD.get(field, field))
            if got != want:
                print("FAIL parse %r\n     %s: got %r, board says %r"
                      % (case["line"][:60], field, got, want))
                failures += 1

    for doc in PARSE["docs"]:
        tasks = todo.parse_doc(doc["text"])
        got = [(t.title, t.bucket, t.column) for t in tasks]
        want = [(t["title"], t["bucket"], t["column"]) for t in doc["tasks"]]
        if got != want:
            print("FAIL parse_doc — %s\n     got  %r\n     want %r"
                  % (doc["why"], got, want))
            failures += 1
            continue
        for t, w in zip(tasks, doc["tasks"]):
            if t.body != w["body"]:
                print("FAIL body of %r\n     got  %r\n     want %r"
                      % (t.title, t.body, w["body"]))
                failures += 1
    print("%d task lines, %d documents — %s"
          % (len(PARSE["cases"]), len(PARSE["docs"]),
             "all agree" if not failures else "%d failed" % failures))
    return failures


def check_priority():
    """Tier one, against the board's own answers.

    The interesting row is med/S beating high/L. That is the counter-intuitive
    half of the rule in PA.md and the one a well-meaning rewrite to
    impact - effort would silently break, so the descending order is pinned as
    well as the individual scores."""
    failures = 0

    class Scored:
        __slots__ = ("impact", "effort")

        def __init__(self, impact, effort):
            self.impact, self.effort = impact, effort

    for case in PRIORITY["cases"]:
        t = Scored(case["impact"], case["effort"])
        if todo.unscored(t) != case["unscored"]:
            print("FAIL unscored %r/%r: got %r, board says %r"
                  % (case["impact"], case["effort"],
                     todo.unscored(t), case["unscored"]))
            failures += 1
        got = todo.priority_score(t)
        if abs(got - case["score"]) > 1e-9:
            print("FAIL score %r/%r: got %r, board says %r"
                  % (case["impact"], case["effort"], got, case["score"]))
            failures += 1

    ranked = sorted(PRIORITY["descending"],
                    key=lambda c: -todo.priority_score(Scored(c["impact"], c["effort"])))
    if [c["impact"] + "/" + c["effort"] for c in ranked] != \
       [c["impact"] + "/" + c["effort"] for c in PRIORITY["descending"]]:
        print("FAIL priority order\n     got  %r\n     want %r"
              % ([c["impact"] + "/" + c["effort"] for c in ranked],
                 [c["impact"] + "/" + c["effort"] for c in PRIORITY["descending"]]))
        failures += 1

    print("%d score combinations, %d ranked — %s"
          % (len(PRIORITY["cases"]), len(PRIORITY["descending"]),
             "all agree" if not failures else "%d failed" % failures))
    return failures


def main():
    failures = 0
    for tag, label, dates, series in CASES:
        rep = todo.read_repeat(tag)
        if label is None:
            if rep is not None:
                print("FAIL %-12s should be rejected, parsed as %s" % (tag, rep))
                failures += 1
            continue
        if rep is None:
            print("FAIL %-12s should parse, was rejected" % tag)
            failures += 1
            continue
        if rep["label"] != label:
            print("FAIL %-12s label %r, board says %r" % (tag, rep["label"], label))
            failures += 1
        got = [todo.occurrence_from(rep, d).isoformat() for d in seeds()]
        for seed, mine, theirs in zip(seeds(), got, dates):
            if mine != theirs:
                print("FAIL %-12s from %s gave %s, board says %s"
                      % (tag, seed, mine, theirs))
                failures += 1
                break
        # And the walk, which is the only thing an interval shows up in.
        cur = todo.occurrence_from(rep, dt.date(2026, 1, 1))
        walked = [cur.isoformat()]
        for _ in range(len(series) - 1):
            cur = todo.occurrence_after(rep, cur)
            walked.append(cur.isoformat())
        for i, (mine, theirs) in enumerate(zip(walked, series)):
            if mine != theirs:
                print("FAIL %-12s occurrence %d gave %s, board says %s"
                      % (tag, i, mine, theirs))
                failures += 1
                break
    checked = sum(len(d) + len(sq) for _, _, d, sq in CASES if d)
    print("%d tags, %d dates — %s"
          % (len(CASES), checked, "all agree" if not failures else "%d failed" % failures))
    failures += check_calendar()
    failures += check_messages()
    failures += check_parse()
    failures += check_priority()
    if "--online" in sys.argv[1:]:
        print("\nAgainst the published sources:")
        failures += check_calendar_online()
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
